name: Build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.7.10'
      - name: Install pip requirements
        run: pip install --no-cache-dir -r requirements.txt -r requirements_tests.txt
      - name: Run flake8 lint
        run: flake8
      - name: Run unit tests
        run: pytest -v tests/
      - name: Test docker build
        run: docker build . --file Dockerfile
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: bumpVersion
        # uses: anothrNick/github-tag-action@1.39.0
        uses: alexeyatbluescape/github-tag-action@bugfix/semver-empty-results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          PRERELEASE_SUFFIX: beta
          WITH_V: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ github.ref == 'refs/heads/master' && 'anclrii/storj-exporter:latest' || '' }}
            ${{ github.ref == 'refs/heads/dev' && 'anclrii/storj-exporter:dev' || '' }}
            anclrii/storj-exporter:${{ steps.bumpVersion.outputs.new_tag }}
          labels: ${{ steps.docker_meta.outputs.labels }}